stages:
  load_data_stage:
    cmd: python -m src.pipelines.load_data --config=config/params.yaml
    deps:
    - src/data/load.py
    - src/data/process.py
    - src/utils/logging.py
    params:
    - config/params.yaml:
      - base
      - data_load
  featurize_stage:
    cmd: python -m src.pipelines.featurize --config=config/params.yaml
    deps:
    - src/data/load.py
    - src/data/process.py
    - src/utils/logging.py
    params:
    - config/params.yaml:
      - base
      - featurize
  train_stage:
    cmd: python -m src.pipelines.train --config=config/params.yaml
    deps:
    - src/evaluate/metrics.py
    - src/train/train.py
    - src/utils/logging.py
    params:
    - config/params.yaml:
      - base
      - featurize.features_path
      - train
    outs:
    - models/model.joblib
    metrics:
    - reports/raw_metrics.csv
    - reports/train_metrics.json
  log_metrics:
    cmd: python -m src.pipelines.log_metrics --config=config/params.yaml
    deps:
    - data/processed/features.feather
    - models/model.joblib
    - reports/raw_metrics.csv
    - reports/train_metrics.json
    params:
    - config/params.yaml:
      - log_metrics
      - train
    outs:
    - reports/mlflow_report.md:
        cache: false
